### ISSUE TITLE
正常获取验证码，通过驱动方法调用chrome等待超时

### ISSUE THREAD

**Issue by redcats2** [yqchilde/JDMemberCloseAccount#133]
**Desc:**

    使用Pycharm调用内置识别，验证码正确获取，但在通过驱动def调用chrome时候似乎异常，表现为等待超时，必现。

**Env:**

    Andriod + MacroDorid + Pycharm 
    Config.yaml:  只打开了debug，其他未更改
    chrome： 94.0.4606.54（正式版本） （64 位） 分别试了94.0.4606.(41/61/113) 

**Debug Log:**

[2022-01-21 00:37:54] [INFO] redcats4 >> 开始注销第 2 家 -> 店铺名: 舒雅京东旗舰店 品牌会员名: 舒雅会员
[2022-01-21 00:37:55] [INFO] redcats4 >> 非当前店铺会员，跳过
[2022-01-21 00:37:55] [INFO] redcats4 >> 开始注销第 3 家 -> 店铺名: 百草味官方旗舰店 品牌会员名: 百草味
[2022-01-21 00:38:00] [INFO] 监听到京东验证码:	621019
[2022-01-21 00:38:00] [INFO] redcats4 >> 验证码监听结果为：621019
[2022-01-21 00:38:33] [ERROR] redcats4 >> 发生了一点小问题：('', None, None)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\JDMemberCloseAccount-main\main.py", line 743, in main
    if not self.close_member(card):
  File "C:\Users\Administrator\Desktop\JDMemberCloseAccount-main\main.py", line 513, in close_member
    if not local_auto_identify_captcha_click():
  File "C:\Users\Administrator\Desktop\JDMemberCloseAccount-main\main.py", line 478, in local_auto_identify_captcha_click
    pcp_show_picture_path_base64 = self.wait.until(EC.presence_of_element_located(
  File "C:\Users\Administrator\Desktop\JDMemberCloseAccount-main\env\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    **raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:** 

[2022-01-21 00:38:33] [INFO] redcats4 >> 开始注销第 4 家 -> 店铺名: 丸美官方旗舰店 品牌会员名: 丸美官方旗舰店

**Comment by yqchilde** [comment]
目前京东更改了图片点选式验证码，改为了轨迹验证码，暂未有对应解决算法

**Comment by redcats2** [comment]
原来如此, 感谢, 看来啥都要赶热乎的...一个月前没弄, 唉

**Comment by yqchilde** [comment]
已更新，请拉取最新代码
