### ISSUE TITLE
main一运行刚加载出来页面就闪退

### ISSUE THREAD

**Issue by Matt-wzy** [yqchilde/JDMemberCloseAccount#149]
[2022-06-02 22:09:47] [ERROR] [main.py:597] 我的pin >> 获取云端列表发生了一点小问题：('Expecting value', '[session-794038ba] Route error: 404 not found!')
Traceback (most recent call last):
  File "C:\Users\wwwa_\Downloads\Telegram Desktop\JDMemberCloseAccount\main.py", line 771, in <module>
    JDMemberCloseAccount().main()
  File "C:\Users\wwwa_\Downloads\Telegram Desktop\JDMemberCloseAccount\main.py", line 640, in main
    state, card_list = self.get_cloud_shop_ids()
TypeError: cannot unpack non-iterable NoneType object

**Comment by fakebri** [comment]
https://github.com/yqchilde/JDMemberCloseAccount/issues/150

**Comment by yqchilde** [comment]
已更新，已去除云端
