### ISSUE TITLE
大佬这个项目已经停止维护了吗？ 出现以下报错

### ISSUE THREAD

**Issue by 2563411574** [yqchilde/JDMemberCloseAccount#150]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\tuihui\main.py", line 771, in <module>
    JDMemberCloseAccount().main()
  File "C:\Users\Administrator\Desktop\tuihui\main.py", line 640, in main
    state, card_list = self.get_cloud_shop_ids()
TypeError: cannot unpack non-iterable NoneType object

**Comment by fakebri** [comment]
这个看一眼就知道了，在main.py的586行`url = "https://gitee.com/yqchilde/Scripts/raw/main/jd/shop.json"`, 因为gitee要求审核，无法访问raw文件，获取不到商铺列表，将url替换为`https://fastly.jsdelivr.net/gh/yqchilde/Scripts@main/jd/shop.json`即可

**Comment by yqchilde** [comment]
已更新，已去除云端
