### ISSUE TITLE
执行python main.py后出现如下

### ISSUE THREAD

**Issue by lplbb** [yqchilde/JDMemberCloseAccount#33]
Traceback (most recent call last):
  File "E:\JDMemberCloseAccount\main.py", line 331, in <module>
    JDMemberCloseAccount().main()
  File "E:\JDMemberCloseAccount\main.py", line 148, in main
    card_list = self.get_shop_cards()
  File "E:\JDMemberCloseAccount\main.py", line 109, in get_shop_cards
    resp = requests.request("POST", url, headers=headers, data=payload)
  File "E:\python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\python39\lib\site-packages\urllib3-1.26.4-py3.9.egg\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by yqchilde** [comment]
解决方案：[ValueError: check_hostname requires server_hostname](https://blog.csdn.net/liboshi123/article/details/116078509)

**Comment by yqchilde** [comment]
尝试关闭代理，或者降低urllib3的版本

**Comment by lplbb** [comment]
已解决，降低urlib3版本
